#!/bin/bash
PACKAGE_NAME=air.com.distriqt.test.debug
APPNAME=../bin-debug/TestNativeMaps
APKNAME=../bin-debug/TestNativeMaps.apk
CERTIFICATE=/path/to/your/certificate.p12
PASSWORD=password
TARGET=apk-debug
EXTDIR=/path/to/ANE/folder
ADT_PATH=adt
ADB_PATH=/Users/shanekorin/work/resources/sdk/android-sdk-macosx/platform-tools/./adb

echo "Building..."
# Compile debug APK using ADT with our p12 certificate
$ADT_PATH -package -target $TARGET -storetype pkcs12 -keystore $CERTIFICATE -storepass $PASSWORD $APKNAME $APPNAME-app.xml $APPNAME.swf ../bin-debug/icons/ ../bin-debug/res/ -extdir $EXTDIR
echo "Finished."



echo "Attempting to install and run application...";
# Uninstall the old version of the app 
$ADB_PATH uninstall $PACKAGE_NAME
# Install new apk
$ADB_PATH install $APKNAME
# Run the app
$ADB_PATH shell am start -a android.intent.action.MAIN -n $PACKAGE_NAME/.AppEntry
echo "Done.";